#!/usr/bin/env bash


## DO NOT EDIT THIS FILE

set -e

if [ $# -ne 5 ]; then
    echo "Usage: run-analysis-one.sh  dirname mainclass tclass tmethod upperbound"
    exit 1
fi

DIRNAME=$1
MAINCLASS=$2
TARGETCLASS=$3
TARGETMETHOD=$4
UPPERBOUND=$5

source environ.sh

echo === running Analysis.java
echo === Points to ANALYSIS

# time java  -Xms800m -Xmx3g Analysis "./target" "AddNumFun" "AddNumFun" "expr"


## clean the output files
rm -f $DIRNAME/$TARGETCLASS.$TARGETMETHOD.output.txt
rm -f $DIRNAME/$TARGETCLASS.$TARGETMETHOD.fulloutput.txt

echo  "=== Running" Analysis "$DIRNAME" "$MAINCLASS"  "$TARGETCLASS"  "$TARGETMETHOD" "$UPPERBOUND"

time \
    java -Xms800m -Xmx3g Analysis "$DIRNAME"  "$MAINCLASS"  "$TARGETCLASS"  "$TARGETMETHOD" "$UPPERBOUND"


dot -Tpng -o cfg.png ${TARGETMETHOD}cfg.dot


errstatus=0
function checkfile() {
    f=$1
    echo === checking for file: $f
    if [ ! -r $f ]; then
        echo "    **** WARNING:  file missing:" $f
        errstatus=-1
    fi
}

# checkfile $DIRNAME/$TARGETCLASS.$TARGETMETHOD.output.txt
# checkfile $DIRNAME/$TARGETCLASS.$TARGETMETHOD.fulloutput.txt

# if any errors, then exit with errorcode
[ $errstatus -eq 0 ] || exit 1

